function [val_before, val_after, duration, delay] = get_sp_generic(block_name)
    val_before = str2double(get_param(strcat('MultiLoop_mode3/', block_name),...
        'SP_before'));
    val_after = str2double(get_param(strcat('MultiLoop_mode3/', block_name),...
        'SP_after'));
    duration = str2double(get_param(strcat('MultiLoop_mode3/', block_name),...
        'deltaT_Ramp'));
    delay = str2double(get_param(strcat('MultiLoop_mode3/', block_name),...
        'tRampStart'));
end

