function [val_before, val_after, duration, delay] = get_sp_generic(block_name)
    val_before = get_param(strcat('MultiLoop_mode3/', block_name),...
        'SP_before');
    val_after = get_param(strcat('MultiLoop_mode3/', block_name),...
        'SP_after');
    duration = get_param(strcat('MultiLoop_mode3/', block_name),...
        'deltaT_Ramp');
    delay = get_param(strcat('MultiLoop_mode3/', block_name),...
        'tRampStart');
end

